### ISSUE TITLE
Order of tasks in report different than in tracker

### ISSUE THREAD

**Issue by Arberesto** [senior-sigan/toggl-reporter#21]
So tasks doesn't sorted by time.

Would prefer for it to be sorted by time, to see in report order of tasks during the day.

**Comment by senior-sigan** [comment]
@Arberesto to add ordering we have to extend this struct: https://github.com/senior-sigan/toggl-reporter/blob/93706601401d140a82c6591c6df2d8ccc49b1a69/report/report.go#L27

This structure stores the hash-map where key is a project description and value is a duration. We have to modify the Value so it would be a <duration, startDate>. Later on the presenter side we could apply sorting by startDate.
