### ISSUE TITLE
Add achievements system

### ISSUE THREAD

**Issue by senior-sigan** [senior-sigan/toggl-reporter#4]
- work > 10 hours in a day
- internal is longer than a real project
- reporting for the previous  month

and so on...

**Comment by Arberesto** [comment]
Should we add database for this feature, to store achievements per user?
Or just ask Toggl API each time to form earned achievements?

With long history asking API can take a lot of time and may limit possible achievements options.

**Comment by Arberesto** [comment]
@senior-sigan

**Comment by senior-sigan** [comment]
> Should we add database for this feature, to store achievements per user? Or just ask Toggl API each time to form earned achievements?
> 
> With long history asking API can take a lot of time and may limit possible achievements options.

As a first iteration or prototype I'd like to see this to be implemented without DB. So I expect achievements to be about "Right now" event without any history.

**Comment by Arberesto** [comment]
Okay.
I think I will add some achievements based on daily, weekly and monthly reports. Should not be hard to achieve.

I've added two daily achievements for now in my fork. Will clean the code and add styles and after that will make PR.

I've created dedicated page for achievements.
Maybe for daily ones will be better to show them on daily report page?

**Comment by Arberesto** [comment]
Added achievements as image icons on same page as reports.

Images can be changed.
UI view can be changed as well if needed - I don't try too hard to make it look good.

@senior-sigan 
Will that be good enough for first iteration?
![report1](https://user-images.githubusercontent.com/33159053/187213213-6e92ce1c-ca2e-49d1-9a5b-9afb4577658a.png)

**Comment by Arberesto** [comment]
We can close it now? Or not? :slightly_smiling_face:

**Comment by Arberesto** [comment]
Actually, found a bug - achievement based on lask week shown for today(Monday). Will check that later.

**Comment by senior-sigan** [comment]
> Actually, found a bug - achievement based on lask week shown for today(Monday). Will check that later.

@Arberesto Please, create a bug issue for this.
